import cx_Oracle


class StudentDatabase:
    def _init_(self, db_host, db_port, db_sid, db_user, db_password):
        """Initialize the Oracle database connection."""
        try:
            # Replace the placeholders with your actual database connection details
            dsn = cx_Oracle.makedsn(db_host, db_port, sid=db_sid)
            self.conn = cx_Oracle.connect(user=db_user, password=db_password, dsn=dsn)
            self.cursor = self.conn.cursor()
        except cx_Oracle.DatabaseError as e:
            print("Database connection error:", e)

    def create_table_if_not_exists(self):
        """Create the students table if it does not exist."""
        try:
            # Using PL/SQL block to handle table creation if it doesn’t exist
            self.cursor.execute('''
                DECLARE
                    table_exists INTEGER := 0;
                BEGIN
                    SELECT COUNT(*) INTO table_exists FROM all_tables WHERE table_name = 'STUDENTS';

                    IF table_exists = 0 THEN
                        EXECUTE IMMEDIATE 'CREATE TABLE students (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR2(50) NOT NULL,
                            roll_no VARCHAR2(20) UNIQUE NOT NULL,
                            grade VARCHAR2(5) NOT NULL
                        )';
                    END IF;
                END;
            ''')
            self.conn.commit()
        except cx_Oracle.DatabaseError as e:
            print("Error in table creation:", e)

    def add_student(self, name, roll_no, grade):
        """Add a new student to the database."""
        if not name or not roll_no or not grade:
            return "All fields must be filled!"

        # Ensure table exists before inserting a new student
        self.create_table_if_not_exists()

        try:
            # Insert student into database
            self.cursor.execute("INSERT INTO students (name, roll_no, grade) VALUES (:1, :2, :3)",
                                (name, roll_no, grade))
            self.conn.commit()
            return "Student added successfully!"
        except cx_Oracle.IntegrityError:
            return "Roll number must be unique!"
        except Exception as e:
            return f"Failed to add student. Error: {str(e)}"

    def view_students(self):
        """Retrieve and display all students from the database."""
        try:
            self.cursor.execute("SELECT name, roll_no, grade FROM students")
            students = self.cursor.fetchall()

            if not students:
                return "No students available."
            else:
                student_list = []
                for student in students:
                    student_list.append(f"Name: {student[0]}, Roll No: {student[1]}, Grade: {student[2]}")
                return "\n".join(student_list)
        except Exception as e:
            return f"Error retrieving students: {str(e)}"

    def close_connection(self):
        """Close the database connection."""
        if hasattr(self, 'conn'):
            self.conn.close()